trackItems:
  ウチはもう、延期できない。_crack.exe:
    displayName: ウチはもう、延期できない。
    categories:
      - common
      - something else

  notepad.exe:
    displayName: notepad
    categories:
      - none
      - cate1

  # Code.exe:
  #   displayName: code
  #   categories:
  #     - none
  #     - vintt

  Tomokoi.exe:
    displayName: tomokoi
    categories:
      - hisagi
      - mizore