trackItems:
  ウチはもう、延期できない。_crack.exe:
    displayName: ウチはもう、延期できない。
    categories:
      - common
      - something else

  notepad.exe:
    displayName: notepad
    categories:
      - none
      - cate1